<template>
  <p class="text-base">
    The use of
    <span class="font-bold text-green-500">artificial intelligence (AI) models</span> like ChatGPT
    is growing rapidly, but the <span class="font-bold">CO2 emissions</span> generated by their
    formation and use are an underappreciated <span class="font-bold">environmental issue</span>.
    These models require enormous amounts of energy to function, especially those that perform
    complex tasks like text generation.
  </p>
  <p class="mt-6">
    According to estimates, <span class="font-bold">ChatGPT</span> emits 8.4 tons of carbon
    dioxide per year, more than twice the amount emitted by an individual. Additionally, a recent
    study revealed the enormous water footprint of AI models like GPT-3, which
    <span class="font-bold">during training consumed 700,000 liters of freshwater</span>,
    equivalent to the production of 320 Tesla vehicles. Despite estimates, there are no explicit
    figures on the total energy consumption of ChatGPT.
  </p>
  <div class="flex justify-center m-8">
    <img alt="AI image" class="w-4/4 sm:w-2/4 shadow-lg rounded-sm" src="@/assets/ai-human.jpg" />
  </div>
  <p class="text-base">
    The rapid growth of the <span class="font-bold">AI sector</span> combined with limited
    transparency makes unknown the total electricity use and carbon emissions attributed to AI. To
    address this issue, it is important to promote
    <span class="font-bold text-green-500">sustainable practices</span> in AI development, such as
    greater <span class="font-bold">transparency and accountability in the development</span> and
    use of machine learning systems. Furthermore, individual efforts to
    <span class="font-bold">recognize the limitations of language models</span> can contribute to
    reducing the environmental costs of AI.    
  </p>
  <p class="mt-6">
    By promoting responsible practices in AI development and research, we can work towards
    creating a more <span class="font-bold">sustainable and equitable future</span>, where
    technological progress does not come at the cost of our planet.
  </p>
  <p class="mt-20">
    Citations:
    <ul class="list-disc ml-6">
      <li>      
        <a
        href="https://earth.org/environmental-impact-chatgpt/"
        target="_blank"
        class="underline text-green-500"
        >
        earth.org
        </a>
      </li>
      <li>      
        <a
        href="https://huggingface.co/blog/carbon-emissions-on-the-hub"
        target="_blank"
        class="underline text-green-500"
        >
        huggingface.co
        </a>
      </li>
    </ul>
  </p>
</template>
